name: Build and Upload Artifact

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build  # 生成 JAR 文件

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: jar-file
          path: build/libs/*.jar  # 上传所有生成的 JAR 文件
