name: Build and Upload Artifact

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # 最新稳定版

      - name: Set up JDK
        uses: actions/setup-java@v4  # 最新稳定版
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'gradle'  # 新增缓存功能

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build --info  # 增加--info查看详细日志

      - name: Upload Artifact
        uses: actions/upload-artifact@v4  # 最新稳定版
        with:
          name: jar-files
          path: |
            build/libs/*.jar
            build/libs/*.pom  # 如果有pom文件也上传
          retention-days: 7  # 自动保留天数
          if-no-files-found: error  # 没有文件时报错
